name: Update Submodules

on:
  workflow_dispatch: # 允许手动触发
  schedule:
    - cron: '10 0 * * *'  # 每天午夜执行

jobs:
  update_submodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true # 确保检出子模块

      - name: Update submodule
        run: git submodule update --remote --recursive

      - name: Check if changes were made
        id: check_changes
        run: |
          if ! git diff --quiet; then
            echo "Changes were made."
            git add .
            git commit -m 'Update submodule'
            git push
          else
            echo "No changes were made."
          fi
