name: Update Submodules

on:
  schedule:
    - cron: '10 0 * * *'  # 每天午夜执行

jobs:
  update_submodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: main
      - name: Update submodule
        run: git submodule update --remote --recursive
      - name: Check if changes were made
        id: check_changes
        run: |
          if git diff --quiet; then
            echo "No changes were made."
          else
            echo "Changes were made."
            git add .
            git commit -m "Update submodule"
            git push
          fi
