name: Update Submodules

on:
  schedule:
    - cron: '10 0 * * *'  # 每天午夜执行

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update submodules
        run: |
          git submodule update --remote --recursive
          git add .
          git commit -m "Update submodules"
          git push
